ARG OS_VER=latest
FROM alpine:${OS_VER}
RUN set -eux;\
    apk --no-cache add\
 bash\
 ccache\
 gcc\
 glib-dev\
 glib-static\
 libc-dev\
 linux-headers\
 make\
 patch\
 perl\
 pixman-dev\
 pixman-static\
 pkgconf\
 python2\
 python3\
 samurai\
 xz\
 zlib-dev\
 zlib-static\
 ;\
    echo DONE
