ARG OS_VER=testing-slim
FROM debian:${OS_VER}
RUN set -eux;\
    apt-get update;\
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends\
 bison\
 build-essential\
 ca-certificates\
 ccache\
 flex\
 g++-mingw-w64\
 gcc\
 git-core\
 libc6-dev\
 make\
 meson\
 mingw-w64-tools\
 mingw-w64-x86-64-dev\
 mingw-w64\
 ninja-build\
 python3-distutils\
 python3\
;\
    apt-get clean; rm -rf /var/lib/apt/lists/*;\
    echo DONE
